const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1100},colorScheme:'light'});const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.PORTPASS_URL||'http://127.0.0.1:8000/');
 await page.waitForSelector('.country');
 assert.equal(await page.locator('.document').count(),0);
 async function add(type,country){await page.click('#add-document');await page.selectOption('#document-type',type);await page.selectOption('#document-country',country);await page.click('button[type=submit]');}
 await add('passport','IN');await add('residence','DE');
 await page.fill('#search','France');await page.click('[data-country=FR]');
 assert.match(await page.locator('#country-detail').innerText(),/Schengen short-stay access/);
 await page.keyboard.press('Escape');await page.click('[data-mode=live]');await page.click('[data-country=FR]');
 assert.match(await page.locator('#country-detail').innerText(),/No residence rule assessed/);
 await page.keyboard.press('Escape');await add('passport','DE');await page.click('[data-country=FR]');
 assert.match(await page.locator('#country-detail').innerText(),/EU freedom of movement/);
 await page.keyboard.press('Escape');await page.reload();await page.waitForSelector('.country');assert.equal(await page.locator('.document').count(),3);
 await page.click('#zoom-in');assert.match(await page.locator('#world-map > g').getAttribute('transform'),/scale\(1.5\)/);
 await page.click('#reset-map');await page.fill('#search','');await page.screenshot({path:'/tmp/portpass-desktop.png',fullPage:true});
 await page.click('#sources-button');assert.equal(await page.locator('#sources-dialog').evaluate(d=>d.open),true);await page.keyboard.press('Escape');
 await page.fill('#search','no-such-country');assert.match(await page.locator('#destination-list').innerText(),/No destinations/);
 await page.fill('#search','');await page.click('#show-more');assert.equal(await page.locator('.destination-card').count(),36);
 await page.click('#show-all');
 const total=await page.evaluate(()=>countries.length);
 assert.equal(await page.locator('.destination-card').count(),total);
 assert.equal(await page.locator('#show-more').isVisible(),false);
 assert.equal(await page.locator('#show-all').isVisible(),false);
 await page.fill('#search','France');assert.equal(await page.locator('.destination-card').count(),1);
 await page.fill('#search','');assert.equal(await page.locator('.destination-card').count(),12);
 await page.click('[data-filter=easy]');
 const filteredTotal=await page.evaluate(()=>countries.filter(c=>groups().find(g=>g.key==='easy').cats.includes(results[c].category)).length);
 if(filteredTotal>12)await page.click('#show-all');
 assert.equal(await page.locator('.destination-card').count(),filteredTotal);
 await page.click('[data-filter=all]');
 const lightFill=await page.locator('.country').first().evaluate(el=>getComputedStyle(el).fill);
 await page.emulateMedia({colorScheme:'dark'});
 await page.waitForTimeout(300);
 assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(23, 30, 43)');
 assert.notEqual(await page.locator('.country').first().evaluate(el=>getComputedStyle(el).fill),lightFill);
 await page.screenshot({path:'/tmp/portpass-desktop-dark.png',fullPage:true});
 await page.click('#add-document');
 assert.equal(await page.locator('#document-country').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(32, 43, 60)');
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/tmp/portpass-mobile-dark.png',fullPage:true});
 await page.emulateMedia({colorScheme:'light'});
 assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(247, 248, 245)');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.screenshot({path:'/tmp/portpass-mobile.png',fullPage:true});
 await page.click('#add-document');await page.selectOption('#document-type','visa');await page.selectOption('#document-country','US');await page.fill('#document-expiry','2020-01-01');await page.click('button[type=submit]');
 assert.match(await page.locator('#documents').innerText(),/Expired/);
 await page.locator('.remove').last().click();assert.equal(await page.locator('.document').count(),3);
 // Agreement routes and passport-specific waiver confirmations use the real form.
 await page.evaluate(()=>localStorage.removeItem('portpass-wallet-v1'));
 await page.reload();await page.waitForSelector('.country');
 await add('passport','GB');await page.click('[data-mode=live]');
 await page.fill('#search','Ireland');await page.click('[data-country=IE]');
 assert.match(await page.locator('#country-detail').innerText(),/Common Travel Area/);
 assert.match(await page.locator('#country-detail a').getAttribute('href'),/gov.uk/);
 await page.keyboard.press('Escape');await page.locator('.remove').click();
 await add('passport','DE');await page.fill('#search','Liechtenstein');await page.click('[data-country=LI]');
 assert.match(await page.locator('#country-detail').innerText(),/Check eligibility/);
 assert.match(await page.locator('#country-detail').innerText(),/quota/);
 await page.keyboard.press('Escape');
 const residenceCounts=await page.locator('.stat strong').allTextContents();
 assert.equal(residenceCounts.reduce((sum,value)=>sum+Number(value),0),199);
 await page.locator('.remove').click();await page.click('[data-mode=visit]');
 await add('passport','UA');await page.fill('#search','France');await page.click('[data-country=FR]');
 assert.match(await page.locator('#country-detail').innerText(),/passport check needed/);
 await page.keyboard.press('Escape');await page.locator('.remove').click();
 await page.click('#add-document');await page.selectOption('#document-country','UA');
 assert.equal(await page.locator('#passport-details').isVisible(),true);
 await page.selectOption('#passport-condition','yes');await page.selectOption('#document-country','MD');
 assert.equal(await page.locator('#passport-condition').inputValue(),'');
 await page.selectOption('#document-country','UA');await page.selectOption('#passport-condition','yes');
 await page.click('button[type=submit]');await page.reload();await page.waitForSelector('.country');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('portpass-wallet-v1'))[0].biometric),true);
 await page.fill('#search','France');await page.click('[data-country=FR]');
 assert.match(await page.locator('#country-detail').innerText(),/You confirmed this condition/);
 await page.keyboard.press('Escape');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 assert.deepEqual(errors,[]);await browser.close();console.log('Browser checks passed: document add/remove, residency boundaries, persistence, dialogs, search, pagination, show all and filters, system theme switching, zoom, mobile overflow, expiry, no JS errors.');
})().catch(e=>{console.error(e);process.exit(1)});
