const assert=require('node:assert/strict');
require('../visa-time.js');require('../rules.js');require('../profile.js');
const P=PortpassProfile,R=PortpassRules,matrix=require('../data/passports.json'),countries=Object.keys(matrix);
const citizen={id:'c',type:'citizenship',country:'DE'};
assert.equal(R.evaluate('DE',[citizen],'live',matrix).category,'home');
assert.equal(R.evaluate('DE',[citizen],'visit',matrix).category,'unknown');
assert.equal(R.evaluate('FR',[citizen],'live',matrix).category,'unknown');
assert.equal(R.evaluate('US',[citizen],'visit',matrix).category,'unknown');
assert.equal(R.activeDocuments([citizen,{type:'visa',country:'US',passport:'DE'}]).length,1);
const wallet=[citizen,{id:'p',type:'passport',country:'IN',biometric:true},{id:'v',type:'schengen',country:'FR',passport:'IN',stayDuration:30,stayUnit:'days',stayBasis:'total',historyComplete:true,visits:[{entry:'2026-01-01',exit:'2026-01-05'}],entryDate:'2026-09-01',expiry:'2027-01-01'}];
assert.deepEqual(P.parse(P.stringify(wallet,'My travel',countries),countries).documents,wallet);
assert.equal(P.parse(P.stringify([])).documents.length,0);
assert.equal(P.filename(''),'profile.portpass');assert.equal(P.filename('   '),'profile.portpass');assert.equal(P.filename('My travels'),'My travels.portpass');assert.equal(P.filename('../test'),'..-test.portpass');
const text=JSON.parse(P.stringify(wallet));
for(const value of [{...text,version:2},{...text,documents:[...wallet,wallet[0]]},{...text,documents:[{...citizen,country:'XX'}]},{...text,documents:[{...wallet[2],stayDuration:-1}]},{...text,documents:[{...wallet[2],visits:[null]}]},{...text,documents:[{...wallet[1],expiry:'2026-02-30'}]}])assert.throws(()=>P.parse(JSON.stringify(value),countries));
assert.throws(()=>P.parse('not a profile'));
assert.throws(()=>P.parse(' '.repeat(P.MAX_BYTES+1)));
const dirty={...citizen,passport:'US',expiry:'bad',extra:'ignored'};
assert.deepEqual(P.parse(P.stringify([dirty])).documents,[citizen]);
console.log('Citizenship isolation, profile round trip, filenames, schema and malformed imports passed.');
