const assert = require('node:assert/strict');
require('../visa-time.js');
require('../rules.js');
const T=globalThis.PortpassVisaTime, R=globalThis.PortpassRules;
const matrix=require('../data/passports.json');
const passport={type:'passport',country:'IN'};
const visa={id:'v',type:'schengen',country:'FR',passport:'IN',entryDate:'2026-09-01',expiry:'2027-01-01',historyComplete:true};
const clock=(v=visa,other=[],date='2026-09-12')=>T.summary(v,[passport,v,...other],matrix,date);
assert.equal(T.day('2026-02-30'),null);
assert.equal(T.iso(T.addMonths(T.day('2024-01-31'),1)),'2024-02-29');
assert.equal(T.iso(T.addMonths(T.day('2026-08-31'),6)),'2027-02-28');
assert.equal(clock().remaining,79);
assert.equal(clock().used,12);
assert.equal(clock().leaveBy,'2026-11-29');
assert.equal(clock().limit.assumed,true);
assert.equal(clock().covers('DE'),true);
assert.equal(clock().covers('IE'),false);
assert.equal(clock({...visa,stayDuration:30,stayUnit:'days'}).remaining,19);
assert.equal(clock({...visa,stayDuration:30,stayUnit:'days'}).limit.assumed,false);
assert.equal(clock({...visa,historyComplete:false,admittedUntil:'2026-12-01'}).remaining,null);
assert.equal(clock({...visa,expiry:'2026-09-20'}).remaining,9);
assert.equal(clock({...visa,entryDate:'2026-09-12',stayDuration:1}).remaining,1);
assert.equal(clock({...visa,entryDate:'2026-09-11',stayDuration:1}).state,'exhausted');
assert.equal(clock({...visa,entryDate:'2026-09-13'}).remaining,null);
const earlier={type:'schengen',country:'DE',passport:'US',expiry:'2026-08-01',visits:[{entry:'2026-06-01',exit:'2026-06-30'}]};
assert.equal(clock(visa,[earlier]).remaining,49);
assert.equal(clock(visa,[earlier,{...earlier,id:'duplicate'}]).remaining,49);
// An old visit drops out day by day, making 79 further days possible, not 67.
const falling={...earlier,visits:[{entry:'2026-03-17',exit:'2026-04-01'}]};
assert.equal(clock(visa,[falling]).remaining,79);
const exhausted={...visa,entryDate:'',stayDuration:10,stayBasis:'total',visits:[{entry:'2026-08-01',exit:'2026-08-10'}]};
assert.equal(clock(exhausted).state,'exhausted');
assert.equal(R.evaluate('DE',[passport,exhausted],'visit',matrix,'2026-09-12').category,'conditional');
assert.equal(R.activeDocuments([passport,{...visa,validFrom:'2026-10-01'}],'2026-09-12').length,1);
const us={type:'visa',country:'US',passport:'IN',entryDate:'2026-08-01',expiry:'2026-08-31',admittedUntil:'2027-01-31'};
assert.equal(clock(us).limit.value,null);
assert.equal(clock(us).state,'expired');
assert.equal(clock(us).remaining,142);
assert.equal(clock({...us,admittedUntil:''}).remaining,null);
assert.equal(T.allowance({...us,passport:'GB'},matrix).value,null);
assert.equal(T.allowance({type:'visa',country:'TH',passport:'IN'},matrix).value,null);
assert.equal(T.allowance({type:'visa',country:'IN',passport:'GB'},matrix).value,30);
const uk={type:'visa',country:'GB',passport:'IN',entryDate:'2026-08-31'};
assert.equal(clock(uk).leaveBy,'2027-02-27');
assert.equal(clock(uk).limit.unit,'months');
assert.equal(T.summary(visa,[visa],matrix,'2026-09-12').state,'unlinked');
assert.equal(clock({...visa,entryDate:'2026-02-30'}).state,'invalid');
assert.equal(clock({...visa,entryDate:'2026-02-30'}).remaining,null);
assert.equal(clock({...visa,visits:[null]}).state,'invalid');
for(const extra of [{stayDuration:0},{stayDuration:1.5},{stayDuration:91},{stayUnit:'months'},{stayBasis:'oops'},{validFrom:'2028-01-01'},{admittedUntil:'2026-08-01'},{visits:[{entry:'2026-08-02',exit:'2026-08-01'}]},{visits:[{entry:'2026-08-01',exit:'2026-08-10'},{entry:'2026-08-10',exit:'2026-08-15'}]}])assert.ok(T.validate({...visa,...extra},'2026-09-12'));
assert.equal(T.validate(visa,'2026-09-12'),'');
console.log('Visa clocks: assumptions, inclusive dates, rolling histories, calendar months, expiry, validation and map routes passed.');
